### ISSUE TITLE
Missing configure script

### ISSUE THREAD

**Issue by knh1** [bortzmeyer/echoping#3]
I could not find any configure script in the source code repository.

~/BUILD/echoping$ find . -name "_config_"
./.git/config
./SRC/configure-common.ac
./SRC/configure.ac
./SRC/contrib/adamsnames/configure.ac
./SRC/contrib/small-services/configure.ac
./SRC/plugins/configure-plugins.ac
./SRC/plugins/configure.ac
./SRC/plugins/dns/configure.ac
./SRC/plugins/ldap/configure.ac
./SRC/plugins/postgresql/configure.ac
./SRC/plugins/random/configure.ac
./SRC/plugins/whois/configure.ac

**Comment by bortzmeyer** [comment]
Yes. The source code in the repository is for developers, you have to generate the configure script with autoconf. Otherwise, use a tarball.
